replicaCount: 2

image:
  repository: lakshmansai/angular-app
  pullPolicy: IfNotPresent
  tag: "8"

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 31055

backend:
  apiUrl: "http://192.168.56.118:31054"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
